import type { Bookmark } from "./bookmark.type"

export const bookmarksData: Bookmark[] = [
    {
        "id": "1",
        "title": "Material-UI (MUI)",
        "url": "https://mui.com/",
        "description": "Popular React UI framework with Material Design components.",
        "faviconUrl": "https://mui.com/static/favicon.ico",
        "tags": ["react", "ui", "material-design", "components"],
        "folder": "UI Libraries",
        "isFavorite": true,
        "createdAt": "2024-01-10T10:00:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "2",
        "title": "Chakra UI",
        "url": "https://chakra-ui.com/",
        "description": "Simple, modular and accessible component library for React.",
        "faviconUrl": "https://chakra-ui.com/favicon.ico",
        "tags": ["react", "ui", "accessibility", "components"],
        "folder": "UI Libraries",
        "isFavorite": true,
        "createdAt": "2024-02-15T12:30:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "3",
        "title": "Ant Design",
        "url": "https://ant.design/",
        "description": "Enterprise-class UI design language and React components.",
        "faviconUrl": "https://ant.design/favicon.ico",
        "tags": ["react", "ui", "enterprise", "components"],
        "folder": "UI Libraries",
        "isFavorite": true,
        "createdAt": "2024-03-05T14:00:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "4",
        "title": "React Bootstrap",
        "url": "https://react-bootstrap.github.io/",
        "description": "Bootstrap rebuilt for React.",
        "faviconUrl": "https://react-bootstrap.github.io/favicon.ico",
        "tags": ["react", "ui", "bootstrap", "components"],
        "folder": "UI Libraries",
        "isFavorite": false,
        "createdAt": "2023-12-20T11:00:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "5",
        "title": "Headless UI",
        "url": "https://headlessui.dev/",
        "description": "Completely unstyled, fully accessible UI components for React.",
        "faviconUrl": "https://headlessui.dev/favicon.ico",
        "tags": ["react", "ui", "headless", "accessibility"],
        "folder": "UI Libraries",
        "isFavorite": true,
        "createdAt": "2024-01-25T09:30:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "6",
        "title": "React Table",
        "url": "https://tanstack.com/table/v8",
        "description": "Headless UI for building powerful tables & datagrids for React.",
        "faviconUrl": "https://tanstack.com/favicon.ico",
        "tags": ["react", "table", "data-grid", "headless"],
        "folder": "UI Libraries",
        "isFavorite": true,
        "createdAt": "2024-03-10T08:45:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "7",
        "title": "React Query",
        "url": "https://tanstack.com/query/v4",
        "description": "Hooks for fetching, caching and updating asynchronous data in React.",
        "faviconUrl": "https://tanstack.com/favicon.ico",
        "tags": ["react", "data-fetching", "hooks", "state-management"],
        "folder": "Tools",
        "isFavorite": true,
        "createdAt": "2024-02-20T15:00:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "8",
        "title": "React Hook Form",
        "url": "https://react-hook-form.com/",
        "description": "Performant, flexible and extensible forms with easy validation.",
        "faviconUrl": "https://react-hook-form.com/favicon.ico",
        "tags": ["react", "forms", "validation", "hooks"],
        "folder": "Tools",
        "isFavorite": true,
        "createdAt": "2024-04-01T11:20:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "9",
        "title": "Framer Motion",
        "url": "https://www.framer.com/motion/",
        "description": "Production-ready motion library for React animations.",
        "faviconUrl": "https://www.framer.com/motion/favicon.ico",
        "tags": ["react", "animation", "motion"],
        "folder": "UI Libraries",
        "isFavorite": false,
        "createdAt": "2024-01-15T13:40:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "10",
        "title": "React Spring",
        "url": "https://react-spring.io/",
        "description": "Spring-physics based animation library for React.",
        "faviconUrl": "https://react-spring.io/favicon.ico",
        "tags": ["react", "animation", "spring"],
        "folder": "UI Libraries",
        "isFavorite": false,
        "createdAt": "2024-03-18T14:50:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "11",
        "title": "React DnD",
        "url": "https://react-dnd.github.io/react-dnd/about",
        "description": "Drag and drop for React with HTML5 backend.",
        "faviconUrl": "https://react-dnd.github.io/favicon.ico",
        "tags": ["react", "drag-and-drop", "ui"],
        "folder": "UI Libraries",
        "isFavorite": false,
        "createdAt": "2024-02-05T10:10:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "12",
        "title": "React Router",
        "url": "https://reactrouter.com/",
        "description": "Declarative routing for React apps.",
        "faviconUrl": "https://reactrouter.com/favicon.ico",
        "tags": ["react", "routing", "navigation"],
        "folder": "Tools",
        "isFavorite": true,
        "createdAt": "2023-11-30T09:00:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "13",
        "title": "Recoil",
        "url": "https://recoiljs.org/",
        "description": "State management library for React apps.",
        "faviconUrl": "https://recoiljs.org/favicon.ico",
        "tags": ["react", "state-management"],
        "folder": "Tools",
        "isFavorite": false,
        "createdAt": "2024-01-05T08:30:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "14",
        "title": "React Spring",
        "url": "https://react-spring.io/",
        "description": "Spring-physics based animation library for React.",
        "faviconUrl": "https://react-spring.io/favicon.ico",
        "tags": ["react", "animation"],
        "folder": "UI Libraries",
        "isFavorite": false,
        "createdAt": "2024-01-15T07:00:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "15",
        "title": "React Virtual",
        "url": "https://react-virtual.tanstack.com/",
        "description": "Virtualization library for efficiently rendering large lists.",
        "faviconUrl": "https://tanstack.com/favicon.ico",
        "tags": ["react", "virtualization", "performance"],
        "folder": "UI Libraries",
        "isFavorite": false,
        "createdAt": "2024-04-10T10:10:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "16",
        "title": "React Use",
        "url": "https://github.com/streamich/react-use",
        "description": "Collection of essential React hooks.",
        "faviconUrl": "https://github.com/favicon.ico",
        "tags": ["react", "hooks", "utilities"],
        "folder": "Tools",
        "isFavorite": true,
        "createdAt": "2024-03-12T09:00:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "17",
        "title": "React Testing Library",
        "url": "https://testing-library.com/docs/react-testing-library/intro",
        "description": "Simple and complete React testing utilities.",
        "faviconUrl": "https://testing-library.com/favicon.ico",
        "tags": ["react", "testing"],
        "folder": "Tools",
        "isFavorite": false,
        "createdAt": "2024-02-01T14:00:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "18",
        "title": "React Hot Toast",
        "url": "https://react-hot-toast.com/",
        "description": "React notifications made easy with beautiful toasts.",
        "faviconUrl": "https://react-hot-toast.com/favicon.ico",
        "tags": ["react", "notifications", "toast"],
        "folder": "UI Libraries",
        "isFavorite": false,
        "createdAt": "2024-01-28T10:00:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "19",
        "title": "React Spring",
        "url": "https://react-spring.io/",
        "description": "Spring-physics based animation library for React.",
        "faviconUrl": "https://react-spring.io/favicon.ico",
        "tags": ["react", "animation"],
        "folder": "UI Libraries",
        "isFavorite": false,
        "createdAt": "2024-04-15T08:00:00Z",
        "contentType": "tool",
        "privacy": "private"
    },
    {
        "id": "20",
        "title": "React Beautiful DnD",
        "url": "https://github.com/atlassian/react-beautiful-dnd",
        "description": "Beautiful and accessible drag and drop for lists with React.",
        "faviconUrl": "https://github.com/favicon.ico",
        "tags": ["react", "drag-and-drop", "ui"],
        "folder": "UI Libraries",
        "isFavorite": false,
        "createdAt": "2024-03-20T12:30:00Z",
        "contentType": "tool",
        "privacy": "private"
    }
]
